name: animidesu
description: Animidesu - cross-platform anime discovery and lawful playback client.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.47.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.5
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
